### ISSUE TITLE
Scrolling is very error-prone

### ISSUE THREAD

**Issue by pushcx** [enwin/emoji#4]
Thanks for making this emoji keyboard, it's been fun to send texts.

Switching the keyboard between its tabs works fine, but I'm having a lot of trouble scrolling the keyboard on the Geeksphone Keon. It takes about five tries to swipe it to the left or right once, and every failed swipe inserts one or more emoji that have to be deleted. (The tab with recently used emoji is a great idea, but getting dozens of extra ones "typed" makes it useless.)

Is there a secret trick to scrolling? Most swipes bring up a little blue highlight bubble - maybe there's a way to tweak the code so that if the touch moves off the key while that's visible the input is cancelled.

**Comment by enwin** [comment]
Thanks for the info, you're not the first one telling me that the swipe is a pain on the Keon.
I'm gonna try to fine tune the swipe detection without compromising the typing delay or try something else to display all the emojis.

**Comment by pushcx** [comment]
I'd love to help - I'm happy to run debug builds or otherwise tinker (though I'm new to FxOS dev, I do have adb set up and I've played with it a bit). Just let me know what would be useful. :)

**Comment by JohanLorenzo** [comment]
Thanks for this keyboard!

I'm also hitting this issue. The scrolling also happens when I want to tap an emoji. In this case, I need to long press an emoji in the middle of the keyboard and move my finger to the emoji I want.

I am one of the Firefox QA guys, feel free to ask me if you need some feedback about a tuning you'd like to test.

**Comment by enwin** [comment]
Hi everyone,

Sorry for my long absence. I just updated the `app` branch https://github.com/enwin/emoji/tree/app with some fixes on the swipe gesture. I hope it will be better for you guys. On my Flame in 2.2 it feels better and the simulators in 2.0, 2.1, and 3.0 are working as well.

All you have to do is to checkout the app branch and add the folder to WebIDE in order to send it to your phone.

Thanks for your feedback!

**Comment by JohanLorenzo** [comment]
I just installed it on a Sony Xperia Z3C with the latest Firefox OS master. At a first glance, the keyboard behaves in a much better way. Thanks @enwin !

I'll keep using it to see if anything other issue comes up.

**Comment by enwin** [comment]
Nice to hear that!
Thanks for testing.

**Comment by enwin** [comment]
The application has been updated on the marketplace with a fix for this one based on the [1.1.1 tag](https://github.com/enwin/emoji/releases/tag/v1.1.1])

Hope its better for everyone now.

**Comment by JohanLorenzo** [comment]
After 10 days with it, I haven't had any issue while typing on the keyboard. Thanks!

**Comment by enwin** [comment]
Great!

I'm closing the issue then.

**Comment by tigny** [comment]
Hi,

I recently acquired a Firefox OS (2.0) Alcatel OneTouch Fire E, and  installed your nice application.
At first i could see a lot of emoji but now it is stuck to 21 emoji per panels. I think the swipe doesn't work at all now, but I think it did the first time I used it... 
I can see there are more emojis waiting thank to the blue underbar on the left.

I hope you can fix that.
