### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by rillian** [enwin/emoji#5]
How can I test the keyboard? I installed deps and ran grunt, which said it was starting a server, but:

```
$ curl http://0.0.0.0:3000/
Cannot GET /
```

Sorry, I don't know much js. Ideally I'd like to install it on my flame.

**Comment by enwin** [comment]
Hi.

Sorry about that, I still haven't pushed the README with the walkthrough to build on your own.

In the meantime congratulations for getting this far!
Running `grunt` only start a webserver but dont build the project. If you just want to build the project you can either run `grunt:dev` or `grunt:release`. The difference is that the `release` task will compress javascript and css.

If you want to make some changes on the code I suggest you to run `npm start` that will run the `dev` task, a webserver, and will watch for modifications in order to rebuild the projet.

In any case the webserver is only usefull to test the html and css of the keyboard the settings page (`settings.html`) as the APIs are not available in Firefox desktop.

The `dev` and `release` tasks build the keyboard in the `app` folder of the project. In order to put it in your phone or in a simulator you'll need to open [WebIDE](https://developer.mozilla.org/en-US/docs/Tools/WebIDE) and import the app folder by opening a packaged app.

Finally, if you only want to install it on your Flame without modifications you can find the keyboard on the [Marketplace](https://marketplace.firefox.com/app/emoji-keyboard) :wink: 

Hope this helps.

Cheers!

**Comment by rillian** [comment]
Thanks, I got it working.
- `npm install`
- `npm install grunt-cli`
- `grunt dev` or `grunt release`

To test: `npm start` and visit the given url (probably http://localhost:3000/) but this isn't functional

To install:
- Open WebIDE from the Firefox Tools developer menu.
- Connect phone or start simulator
- Select 'Open Packaged app...'
- open the `app` directory with manifest.webapp and settings.html
- click the ▶︎ button

I was also able to install the one from the Marketplace. Any suggestion how to _uninstall_ keyboards? There's no icon on the launch screen I can long-press on.

**Comment by enwin** [comment]
I promise I'm gonna push that README (one day or another).

Uninstalling an app (other than a launch screen app) is not tricky at all, you just need to find the right panel. In our case all installed app are listed in the **settings** app of the phone under the **App permissions** category. In this category you'll find all installed apps and you'll be able to change their permissions, like geolocation, and delete them.

Enjoy the keyboard!

**Comment by rillian** [comment]
Thanks! Never occured to me to look there for a remove button.

Have you submitted this for inclusion in upstream gaia? Seems like the sort of thing which should be standard.

**Comment by rillian** [comment]
Mozilla bug for an emoji keyboard is https://bugzilla.mozilla.org/show_bug.cgi?id=993899

**Comment by enwin** [comment]
Yes saw that. I'm in the CC list for a while now and thats the reason why I started to develop the keyboard as it was constantly pushed to the next version.

Thanks for your message over there by the way ;)
